{% set name = "wetterdienst" %}
{% set version = "0.111.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wetterdienst-{{ version }}.tar.gz
  sha256: 0f7b38aae930095e8c84a6305345f94251b4bd8e4ee71202daa39b3c0e232409

build:
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

outputs:
  - name: {{ name }}
    script: install_wetterdienst.sh
    build:
      noarch: python
      entry_points:
        - wetterdienst = wetterdienst.ui.cli:cli
        - wddump = wetterdienst.provider.dwd.radar.cli:wddump

    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }},<4.0
        # for python < 3.11 but we want to stay noarch
        - backports-datetime-fromisoformat >=2
        - click >=8,<9
        - cloup >=3.0.1,<4
        - diskcache >=5.4,<6

        - fsspec >=2023.1
        # fsspec[http]
        - aiohttp !=4.0.0a0,!=4.0.0a1

        - lxml >=4.9.1,<7
        - measurement >=3.2,<4
        - platformdirs >=4,<5

        - polars >=1.0.0,<2
        # polars[calamine,pyarrow]
        - fastexcel >=0.9
        - pyarrow >=7.0.0

        - portion >=2.4.2,<3
        - pydantic >=2.7.3,<3
        - pydantic-extra-types >=2.10.1,<3
        - pydantic-settings >=2.7.0,<3
        - pypdf >=3.12.1,<6
        - python-dateutil >=2,<3
        - rapidfuzz >=3.1,<4
        - stamina >=23,<26
        - tabulate >=0.8,<1
        - tqdm >=4,<5
        - python-tzdata >=2024.2
        - tzfpy >=0.15.2,<2

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
        - wetterdienst --help
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}-with-bufr
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - pdbufr >=0.10.2,<1
        - pybufrkit >=0.2,<1

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  # sqlalchemy-cratedb not on conda-forge
  # - name: {{ name }}-with-cratedb
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python {{ python_min }}
  #     run:
  #       - python >={{ python_min }}
  #       - {{ pin_subpackage(name, exact=True) }}
  #       - pandas >=2,<3
  #       - sqlalchemy-cratedb <1

  #   test:
  #     imports:
  #       - wetterdienst
  #     commands:
  #       - pip check
  #     requires:
  #       - python {{ python_min }}
  #       - pip

  - name: {{ name }}-with-duckdb
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - duckdb >=0.9,<2
        - pandas >=2,<3

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-eccodes
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - python-eccodes >=1.5.2,<3

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-excel
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - xlsxwriter >=3.0.9,<4

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-explorer
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - duckdb >=0.9,<2
        - plotly >=5.11,<7
        - statsmodels >=0.14.1,<1
        - streamlit >=1.27,<2

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-export
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - pandas >=2,<3
        - sqlalchemy >=2,<3
        - xarray >=2023.1,<2026
        - xlsxwriter >=3.0.9,<4
        # let's see if we can still include this with python 3.10
        # because otherwise we can't stay noarch: python 
        - zarr >=3.1,<4

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  # - name: {{ name }}-with-influxdb
  #   build:
  #     noarch: python
  #   requirements:
  #     host:
  #       - python {{ python_min }}
  #     run:
  #       - python >={{ python_min }}
  #       - {{ pin_subpackage(name, exact=True) }}
  #       - influxdb >=5.3,<6
  #       - influxdb-client >=1.18,<2
  #       - influxdb3-python >=0.3,<1

  #   test:
  #     imports:
  #       - wetterdienst
  #     commands:
  #       - pip check
  #     requires:
  #       - python {{ python_min }}
  #       - pip

  - name: {{ name }}-with-interpolation
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - scipy >=1.14.1,<2
        - shapely >=2,<3
        - utm >=0.7,<1

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-matplotlib
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - matplotlib-base >=3.3,<4

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-mysql
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - mysqlclient >=2,<3
        - pandas >=2,<3

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-plotting
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - python-kaleido >=0.2.2
        - plotly >=5.24.1

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-postgresql
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - psycopg2-binary >=2,<3

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-radar
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - h5py >=3.1,<4

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-radarplus
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - pybufrkit >=0.2,<1
        - wradlib >=2.0.1,<3
        - xradar >=0.2,<1

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-restapi
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - fastapi >=0.95.1,<1
        - httpx >=0.24,<1
        - uvicorn-standard >=0.14,<1

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-sql
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, exact=True) }}
        - duckdb >=0.9,<2

    test:
      imports:
        - wetterdienst
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  feedstock-name: wetterdienst
  recipe-maintainers:
    - xylar
    - amotl
    - gutzbenj
    - kmuehlbauer
