{% set name = "wetterdienst" %}
{% set version = "0.73.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wetterdienst-{{ version }}.tar.gz
  sha256: bcfc54817a644937b59d5502957b20dc4bef5a28f65bce9610f68be5bf2d239b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9,<4.0
    - aenum >=3,<3.2
    - aiohttp >=3.8,<3.10
    - backports-datetime-fromisoformat >=2,<3
    - beautifulsoup4 >=4.9,<5
    - cachetools >=5.2,<6
    - click >=8,<9
    - click-params >=0.4.1,<5
    - cloup >=3.0.1,<4
    - deprecation >=2.1,<3
    - diskcache >=5.4.0,<6
    - environs >=9.4.0,<11
    - fsspec >=2023.1,<2023.13
    - lxml >=4.9.1,<6
    - measurement >=3.2,<4
    - numpy >=1.22,<1.27
    - pandas >=2,<2.2
    - pint >=0.17,<0.24
    - platformdirs <5
    - polars >=0.20.6,<0.20.7
    - portion >=2.4.2
    - pyarrow >=13,<16
    - pypdf >=3.12.1,<4.1
    - python-dateutil <3
    - rapidfuzz >=3.1,<4
    - requests >=2.20,<3
    - scikit-learn >=1.0.2,<1.5
    - stamina >=23,<25
    - tabulate >=0.8,<0.10
    - tqdm >=4,<5
    - tzfpy >=0.15.2,<1
    - xlsx2csv >=0.8.1,<0.9
    - xlsxwriter >=3.0.9,<3.2
    - python-eccodes >=1.5.2,<1.7

test:
  imports:
    - wetterdienst
  commands:
    - pip check
    - wetterdienst --help
  requires:
    - pip

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - xylar
    - amotl
    - gutzbenj
    - kmuehlbauer
