{% set name = "wetterdienst" %}
{% set version = "0.70.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wetterdienst-{{ version }}.tar.gz
  sha256: bf4ac93c71bfbeac846677dae53947e7e79aab5a7cfa36a60c5cb8f6646d51e5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.9,<3.12
    - poetry-core
    - pip
  run:
    - crate >=0.30.1,<1optionaltrue
    - dash >=2.10,<2.15optionaltrue
    - dash-bootstrap-components >=1.4,<2optionaltrue
    - dash-leaflet >=1.0.8,<2optionaltrue
    - duckdb >=0.9,<0.10optionaltrue
    - eccodes >=1.5.2,<1.7optionaltrue
    - fastapi >=0.95.1,<0.104optionaltrue
    - geojson >=3,<4optionaltrue
    - h5py >=3.1,<4optionaltrue
    - httpx >=0.24,<0.27optionaltrue
    - influxdb >=5.3,<6optionaltrue
    - influxdb-client >=1.18,<2optionaltrue
    - influxdb3-python >=0.3.0,<1optionaltrue
    - matplotlib-base >=3.3,<3.9optionaltrue
    - mysqlclient >=2,<3optionaltrue
    - openpyxl >=3,<4optionaltrue
    - plotly >=5.11,<6optionaltrue
    - psycopg2-binary >=2.8,<3optionaltrue
    - scipy >=1.9,<1.12optionaltrue
    - shapely >=2,<3optionaltrue
    - sqlalchemy >=2,<2.1optionaltrue
    - streamlit >=1.27,<2optionaltrue
    - utm >=0.7,<1optionaltrue
    - uvicorn >=0.14,<1optionaltrue
    - wradlib >=2.0.1,<3optionaltrue
    - xarray >=2023.1,<2023.11optionaltrue
    - xradar >=0.2,<0.5optionaltrue
    - zarr >=2.13,<3optionaltrue
    - python >=3.9.0,<4.0.0,!=3.9.7,<3.12
    - aenum >=3,<3.2
    - aiohttp >=3.8,<3.10
    - backports-datetime-fromisoformat >=2,<3
    - beautifulsoup4 >=4.9,<5
    - cachetools >=5.2,<6
    - click >=8,<9
    - click-params >=0.4.1,<5
    - cloup >=3.0.1,<4
    - deprecation >=2.1,<3
    - diskcache >=5.4.0,<6
    - environs >=9.4.0,<10
    - fsspec >=2023.1,<2023.11
    - lxml >=4.9.1,<5
    - measurement >=3.2,<4
    - numpy >=1.22,<1.27
    - pandas >=2,<2.2
    - pint >=0.17,<0.23
    - platformdirs <4
    - polars >=0.19.6,<0.20
    - pyarrow >=13,<15
    - pypdf >=3.12.1,<3.18
    - python-dateutil <3
    - rapidfuzz >=3.1,<4
    - requests >=2.20,<3
    - scikit-learn >=1.0.2,<1.4
    - stamina >=23,<24
    - tabulate >=0.8,<0.10
    - tqdm >=4,<5
    - tzfpy >=0.15.2,<1
    - xlsx2csv >=0.8.1,<0.9
    - xlsxwriter >=3.0.9,<3.2
    - python-eccodes >=1.5.2,<1.7

test:
  imports:
    - wetterdienst
  commands:
    - pip check
    - wetterdienst --help
  requires:
    - pip

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - xylar
    - amotl
    - gutzbenj
    - kmuehlbauer
