{% set name = "wetterdienst" %}
{% set version = "0.59.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wetterdienst-{{ version }}.tar.gz
  sha256: e9b3b3db1c54d1c3cdd7259592af87b0c2f0924b9f4c9952b26f8761707623ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.9,<3.12
    - pip
    - poetry-core
  run:
    - python >=3.9,<3.12
    - aenum >=3.0,<4.0
    - aiohttp >=3.8.1,<4.0.0
    - backports-datetime-fromisoformat >=2.0.0,<3.0.0
    - beautifulsoup4 >=4.9.0,<5.0.0
    - cachetools >=5.2.0,<6.0.0
    - click >=8.0.0,<9.0.0
    - click-params >=0.4.1,<0.5.0
    - cloup >=2.0.0,<3.0.0
    - deprecation >=2.1.0,<3.0.0
    - diskcache >=5.4.0,<6.0.0
    - environs >=9.4.0,<10.0.0
    - fsspec >=2023.01,<2024.0
    - lxml >=4.9.1,<5.0.0
    - measurement >=3.2.0,<4.0.0
    - numpy >=1.22.0,<2.0.0
    - pandas >=2.0.0,<3.0.0
    - pint >=0.17.0,<0.18.0
    - platformdirs >=3.8.0,<4.0.0
    - polars >=0.16.0,<0.17.0
    - pyarrow >=12.0.0,<13.0.0
    - pypdf >=3.12.1,<4.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - rapidfuzz >=3.1.0,<4.0.0
    - requests >=2.20.0,<3.0.0
    - scikit-learn >=1.0.2,<2.0.0
    - stamina >=23.1.0,<24.0.0
    - tabulate >=0.8.0,<0.9.0
    - timezonefinder >=6.1.0,<7.0.0
    - tqdm >=4.47.0,<5.0.0
    - python-tzdata >=2023.3.0,<2024.0.0
    - xlsx2csv >=0.8.1,<0.9.0
    - xlsxwriter >=3.0.9,<4.0.0
    - python-eccodes >=1.5.2,<2.0.0

test:
  imports:
    - wetterdienst
  commands:
    - pip check
    - wetterdienst --help
  requires:
    - pip

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - xylar
    - amotl
    - gutzbenj
    - kmuehlbauer
