{% set name = "wetterdienst" %}
{% set version = "0.98.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wetterdienst-{{ version }}.tar.gz
  sha256: ba75bc4db2b8a457d36393eee9a4a2d33cbf4ed61166a0dc42e191766624b189

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - fastexcel >=0.10.4
    - pydantic >=2.7.3
    - python >={{ python_min }},<4.0
    - aenum >=3
    - aiohttp >=3.8
    - backports-datetime-fromisoformat >=2,<3
    - beautifulsoup4 >=4.9
    - cachetools >=5.2
    - click >=8
    - click-params >=0.4.1
    - cloup >=3.0.1
    - deprecation >=2.1
    - diskcache >=5.4
    - environs >=9.4
    # for python < 3.10 but we want to stay noarch: python
    - eval-type-backport >=0.1.3,<0.2.0
    - fsspec >=2023.1
    - lxml >=4.9.1
    - measurement >=3.2
    - numpy >=1.22
    - pillow >=10.3
    - pint >=0.17
    - platformdirs
    - polars >=1.0.0
    - portion >=2.4.2
    - pyarrow >=13
    - pypdf >=3.12.1
    - python-dateutil
    - rapidfuzz >=3.1
    - requests >=2.20
    - scikit-learn >=1.0.2
    - stamina >=23
    - tabulate >=0.8
    - tqdm >=4
    - tzfpy >=0.15.2
  run_constrained:
    - duckdb >=0.9
    - python-eccodes >=1.5.2,<1.7
    - fastapi >=0.95.1,<0.110
    - httpx >=0.24,<0.27
    - h5py >=3.1,<4
    - influxdb >=5.3,<6
    - influxdb-client >=1.18,<2
    - influxdb3-python >=0.3.0,<1
    - matplotlib-base >=3.3,<3.9
    - mysqlclient >=2,<3
    - openpyxl >=3,<4
    - pandas >=2,<2.2
    - pdbufr >=0.10.2,<0.12
    - plotly >=5.11,<6
    - psycopg2-binary >=2.8,<3
    - scipy >=1.14.1
    - shapely >=2,<3
    - sqlalchemy >=2,<2.1
    - sqlalchemy-cratedb >=0.37.0,<1
    - statsmodels >=0.14.1
    - streamlit >=1.27,<2
    - utm >=0.7,<1
    - uvicorn >=0.14,<1
    - wradlib >=2.0.1,<3
    - xarray >=2023.1,<2024.2
    - fastexcel >=0.10.4
    - xlsxwriter >=3.0.9,<3.2
    - xradar >=0.2,<0.5
    - zarr >=2.13,<3

test:
  imports:
    - wetterdienst
  commands:
    - pip check
    - wetterdienst --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - xylar
    - amotl
    - gutzbenj
    - kmuehlbauer
